### ISSUE TITLE
HTTP Error 503

### ISSUE THREAD

**Issue by JamPat17** [ShiftHackZ/Stable-Diffusion-Android#100]
I understand its in beta but local diffusion just returns the answer ERROR: HTTP 503

**To Reproduce**
1. Open app
2. Select local diffusion
3. Select download

**Expected Behavior**
It would download the ai model.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 14 

**Smartphone (please complete the following information):**
 - Device: Note 10+ 5g
 - OS: Android 14
 - Browser Chrome

**Comment by firen777** [comment]
Seems like the app trying to fetch https://share.moroz.cc/SDAI/chilloutmix.zip and get 503. Hopefully it's not related to:

> ... the SDAI Cloud may not be available full-time, as this is running on the app author's own bare-metal machine which is hosted in Ukraine, as this area now is a warzone electricity and network downtimes can happen sometimes.

**Comment by Cbender86** [comment]
I can confirm, the Server seems to be down. However, the chilloutmix model is available at https://civitai.com/models/6424/chilloutmix, can you install it manually?

**Comment by JamPat17** [comment]
hm, do you know how id go about doing this manually?

**Comment by JamPat17** [comment]
where would i place the model after downloading it?

**Comment by zayn1991** [comment]
I think that you won’t even understand what kind of files these are in the zip archive
It doesn't look like the models from the Civitai website.
And the archive dosen't has ***.safetensors** files

![scr1](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/17571172/68826f21-e47c-4a35-8d22-3b7ae8fa3500)
![scr2](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/17571172/18578025-e18c-4654-b18f-bb918e3bc7a8)
![scr3](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/17571172/17b88594-543d-46a8-961b-02b7ace40e44)

**Comment by ShiftHackZ** [comment]
Server is back now, but I can't guarantee it won't be down at some point.
