### ISSUE TITLE
Can't click on local diffusion 

### ISSUE THREAD

**Issue by Ar57m** [ShiftHackZ/Stable-Diffusion-Android#117]
I'm on Android 13 (Galaxy M52 5G), latest version 0.5.4, both google play and FOSS version.

https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/132871733/743a55cc-1c70-42c6-bfd8-d5aa97c4cdd5

**Comment by madijason** [comment]
The configuration page isn't even showing on EMUI 13. Cannot set to local.

**Comment by ShiftHackZ** [comment]
Hello, try re-downloading updated version that released today and please let us know if it works for you.
https://github.com/ShiftHackZ/Stable-Diffusion-Android/releases/tag/0.5.4

**Comment by Ar57m** [comment]
> Hello, try re-downloading updated version that released today and please let us know if it works for you. https://github.com/ShiftHackZ/Stable-Diffusion-Android/releases/tag/0.5.4

thanks 🤗 now is working fine for me
