### ISSUE TITLE
Add popup before model deletion

### ISSUE THREAD

**Issue by Patrick762** [ShiftHackZ/Stable-Diffusion-Android#143]
**Is your feature request related to a problem? Please describe.**
I tested a few of the local diffusion models and accidentaly clicked on delete, which instantly deleted the model.

**Describe the solution you'd like**
Add a popup to make sure the model isn't deleted by accident.

**Describe alternatives you've considered**
None

**Comment by ShiftHackZ** [comment]
Implemented in app version [0.5.11](https://github.com/ShiftHackZ/Stable-Diffusion-Android/releases/tag/0.5.11).
