### ISSUE TITLE
I don't have all the features 

### ISSUE THREAD

**Issue by KintCark** [ShiftHackZ/Stable-Diffusion-Android#158]
I'm missing features I saw someone had a custom model feature something is wrong here idk if it's my android version I'm got android 13 one ui 5.0

**Comment by KintCark** [comment]
I just had to clear my cache thx

**Comment by ShiftHackZ** [comment]
Install FOSS version from F-Droid or GitHub releases, app installed from Google Play won't have this feature.

For reference please see the differences between FOSS and PLAYSTORE builds: https://github.com/ShiftHackZ/Stable-Diffusion-Android?tab=readme-ov-file#difference-between-builds-from-google-play-and-f-droidgithub-releases
