### ISSUE TITLE
ort model repository, or .safetensors option.

### ISSUE THREAD

**Issue by tomatesyverduras** [ShiftHackZ/Stable-Diffusion-Android#165]
Currently it is difficult to find models with the .ort extension. Please add a link to somewhere where can download models, or be able to use models .safetensors.  thanks for the app.

**Comment by ShiftHackZ** [comment]
Latest app version contains a built-in list of models available for download.

![image](https://github.com/user-attachments/assets/1a67a857-0fe9-44ca-99a8-9b282163fc24)

The in-app models are hosted here: https://github.com/ShiftHackZ/Local-Diffusion-Models-SDAI-ONXX

Alternatively, you can find some online (for example here: https://huggingface.co/Androidonnxfork/test/tree/main/fp16fullonnxsdquantized_in_ort).
