### ISSUE TITLE
Export input picture

### ISSUE THREAD

**Issue by seedlord** [ShiftHackZ/Stable-Diffusion-Android#187]
after generating an image with img2img there is no way to save the input image into the phone gallery. I can view it in the app "gallery"-tab.

it would be nice to have the input image saved automatically in phone gallery or make it possible to export it manually.

**Comment by ShiftHackZ** [comment]
It will work this way: if user is on gallery detail tab, and clicks Export button on the toolbar, app will export image depending on the currently selected bottom tab:
- If user is on the `Image` tab, app will export generated image;
- If user is on the `Original` tab, app will export input image.
