### ISSUE TITLE
Local Model Downloads Directory

### ISSUE THREAD

**Issue by SatoX69** [ShiftHackZ/Stable-Diffusion-Android#212]
**This is not a BUG report.**

Hi, Can anyone tell me how to add a custom downloaded model from a different directory to the app (I'm fine with moving the model over to whatever directory this may need)
Like suppose I downloaded a model, how to install it on the app instead of the default ones it provides and what format or other model stuff this app supports?

**Comment by ShiftHackZ** [comment]
Hi, here is how to sideload a custom model:
- Make sure you installed SDAI FOSS (either from GitHub apk or F-Droid, build from Google Play does not allow model sideloading)
- Navigate to your default `Download` directory in internal storage.
  - Create `SDAI` directory (if it's not already there)
  - Inside `SDAI` directory create `model` directory.
- Inside `Download/SDAI/model` directory place the folders/files from downloaded model, there should be at least 4 directories: text_encoder, tokenizer, unet, vae_decoder (see screenshot for example)

![image](https://github.com/user-attachments/assets/24401698-5988-4d25-b3db-9a94e9035c00)
![image](https://github.com/user-attachments/assets/56a16bc7-0f8d-4e72-8f1c-5ce605ed3d3e)

- In the SDAI foss select `Local Diffusion` generation provider.
- On the configure page, set:
  - Enable `Load custom model`
  - Click `Setup permission`, Select SDAI FOSS, Enable `Allow access to manage all files` 
  
![image](https://github.com/user-attachments/assets/00310673-5cba-4e61-9ec1-fc88776e3ae6)
![image](https://github.com/user-attachments/assets/236edef2-7e4e-4c0d-9d9f-2a9158d9630e)
![image](https://github.com/user-attachments/assets/0b141224-cd56-4081-a309-a470ca8052f2)

- Return back to app, scroll down, click `Setup`
- Try to generate something in txt2img mode, if model loaded you will see progress pop up, and after a while a generated image

![image](https://github.com/user-attachments/assets/4b83d30a-c224-4835-82d9-25de84564a42)
![image](https://github.com/user-attachments/assets/3052b468-3410-4a1c-a301-4534f6a7d831)

Please note that Local Diffusion is experimental beta feature, you may experience slow performance and/or some crashes depending on model and android device.

**Comment by ShiftHackZ** [comment]
Regarding supported models - only onnx models are supported (those that have *.ort format).
You can find the sources for all models that are available in app for download in this repository: https://github.com/ShiftHackZ/Local-Diffusion-Models-SDAI-ONXX

**Comment by SatoX69** [comment]
Hey mate,

The app is working fine. I downloaded one of the predefined models, and it was running smoothly. However, I have a problem: my internal storage is running low, so I want to use the app to load custom models from my SD card. I also don't want to install another model manually. Instead, I want to move the already installed model (that I installed from the app) to my SD card. But I can't find the package named file anywhere in Android/data or obb, either on the SD card or internal storage (com.shifthackz.aisdv1.app.foss). Can you tell me which directory I can access the downloaded models in?

And no, I haven't installed any custom models yet.
