### ISSUE TITLE
URL errorr

### ISSUE THREAD

**Issue by ghost** [ShiftHackZ/Stable-Diffusion-Android#51]
**Describe the bug**
I tried following the procedure described on the ap page but it doesn't work I had to add --share to get a public url.

**To Reproduce**
1. enter as argument  in 'webui_user.bat': --xformers --autolaunch --opt-split-attention --precision full --no-half --medvram --share --api --listen
2. Copy and paste from CMD the public URL (sample: https://02c0c88cb5143e3673.gradio.live:7860) into the app
3. Click on 'Connect'
5. See error 404

**Expected behavior**
As written in the guide I expected to start the interface where to generate the images

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera Developer
 - Version: 101.0.4822.0

**Smartphone (please complete the following information):**
 - Device: Realme GT 5G
 - OS: Android 13
 - Browser: Your App (Playstore version and GitHub version )
 - Version IDK

**Comment by kuso-ge** [comment]
You have to access it using your host computer's ipv4 address and not the one used by Auto1111.

**Comment by umut-ore** [comment]
Also you may possibly need to enable port forwarding to your computer in your router/modem depending on your configuration.

**Comment by ShiftHackZ** [comment]
Hi @ghost, thanks for reporting this issue.
Error 404 means that some of automatic1111 api calls was not found on your instance.

Please, check that:
- You are running latest official automatic1111 software with flags --api --listen
- In case you are connecting to your local computer, check that firewall is not blocking 7860 port, phone is on the same local network with computer, and you are using your computer's LAN IP address to connect.

In case this does not work for you, please try and tell us if:
- Update SDAI app to the latest version.
- Check if you can connect to cloud services (SDAI or Horde) and if they work for you.

Also please attach logs of your 404 error, to export logs go to "Settings" tab, and press "Report a problem" button, then send a letter to sdai@moroz.cc.

**Comment by ShiftHackZ** [comment]
Closing, due to inactivity.
