### ISSUE TITLE
Request: Apache Proxy Basic Auth Support

### ISSUE THREAD

**Issue by umut-ore** [ShiftHackZ/Stable-Diffusion-Android#56]
**Is your feature request related to a problem? Please describe.**
I can not add my A1111 instance because you need to authenticate beforehand using apache's basic auth, like the following url structure: https://username:password@mydomain.com

**Describe the solution you'd like**
A way to be able to use the auth and proxy.

**Describe alternatives you've considered**
None, to be honest.

**Comment by ShiftHackZ** [comment]
Hi, @umut-ore ! Thanks for your feature request! 
Could you please provide your apache2 configuration example, so I can replicate the same configuration on my end for testing purpose ?

**Comment by umut-ore** [comment]
<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile "cert.pem"
    SSLCertificateKeyFile "key.pem"
    SSLCertificateChainFile "chain.pem"
    
    SSLProxyEngine On
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    

    ProxyPreserveHost On
    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass / wss://127.0.0.1:7860/
    ProxyPassReverse / wss://127.0.0.1:7860/
    ProxyPass / https://127.0.0.1:7860/
    ProxyPassReverse / https://127.0.0.1:7860/

    <Location />
        AuthType Basic
        AuthName "Restricted Access"
        AuthUserFile ".htpasswd"
        Require valid-user
    </Location>	
    
    ServerName yourdomain.com
    ErrorLog "error.log"
    CustomLog "access.log" common
</VirtualHost>

**Comment by ShiftHackZ** [comment]
Implemented HTTP Basic auth in latest 0.4.2.
Here is a configuration example: 
![зображення](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/41302477/e0850488-3fc0-46ef-97a2-d0f23709568c)

**Comment by umut-ore** [comment]
Thank you so much mate!
