### ISSUE TITLE
when you click on a result, open the photo in full, large mode

### ISSUE THREAD

**Issue by Wjxfi** [ShiftHackZ/Stable-Diffusion-Android#69]
![c04c6026-e51f-44fe-8589-99b8a666bbbe.jpg](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/113500363/1fc50bfd-6c50-4399-a1c7-986ac74cc680)

**Comment by ShiftHackZ** [comment]
Thanks for your feature request. 
It makes sense to open photo in gallery by clicking it.
The only problem here if user disables auto-save option, this dialog will show generation image with "Save" button, but if user clicks on photo before clicking the "Save" button - it won't be in DB, and Gallery Detail screen won't load it. I'll think about workarounds.
