### ISSUE TITLE
Add f-droid like this

### ISSUE THREAD

**Issue by Wjxfi** [ShiftHackZ/Stable-Diffusion-Android#70]
![356e7c50-f9ea-4ea0-a08c-5376868483e5.jpg](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/113500363/560a1a11-2ab2-4d89-8c8d-7b1c531832b4)

**Comment by ShiftHackZ** [comment]
For now application is not available on fdroid, it is in process of passing the review. 
The badge will be added as soon as app will be approved and included in fdroid data repository.
The review process is open to public, and is available in [this PR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13411).

**Comment by IzzySoft** [comment]
@ShiftHackZ and please remove the IzzyOnDroid badge now that your app is on F-Droid: I just removed the app here as the APK size clearly exceeds the 30-MB-per-App limit more than once :wink: (No idea what caused the jump from 14 MB to 72 MB) Thanks!

**Comment by IzzySoft** [comment]
Ah, so the part that previously needed to run on a server is no included with the app, no server needed anymore? OK, that explains then, thanks!
