### ISSUE TITLE
Text Generation Webui

### ISSUE THREAD

**Issue by Dartvauder** [ShiftHackZ/Stable-Diffusion-Android#85]
Good afternoon. Thanks for your project. But I would like to ask you to add the possibility to use this https://github.com/oobabooga/text-generation-webui

The application works identically to automatic 1111. I would really like to use a good chat ai on the phone instead of chatgpt.

Thank you in advance and good luck!

P.S. For example, you can add tabs where we select automatic1111 or text generation ai

**Comment by ShiftHackZ** [comment]
Hi @Dartvauder! Thanks for your question. 

I have looked through documentation of **[text-generation-webui](https://github.com/oobabooga/text-generation-webui)** and found that it also contains **--api** flag, so I believe it's possible to develop a mobile app that can work with deployed instance of that project. 

But I also sure that is's out of scope for this application, goal of SDAI application to support Stable Diffusion Image generation mainly, and I don't want to overload this app with functionality not related to image generation. It is better to develop a separate app that will be responsible for text generation specifically.

**Comment by Dartvauder** [comment]
Thanks for your reply @ShiftHackZ . I really hope that you will find the time to develop a separate application for text AI. Good luck with your developments!
