### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by licaon-kter** [ShiftHackZ/Stable-Diffusion-Android#94]
ref: https://monitor.f-droid.org/builds/log/com.shifthackz.aisdv1.app.foss/165#site-footer

Local APK:
[com.shifthackz.aisdv1.app.foss_165.7z.001.zip](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12619075/com.shifthackz.aisdv1.app.foss_165.7z.001.zip)
[com.shifthackz.aisdv1.app.foss_165.7z.002.zip](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12619076/com.shifthackz.aisdv1.app.foss_165.7z.002.zip)
(remove `.zip` from both names, then unpack `.001`)

Upstream APK: https://github.com/ShiftHackZ/Stable-Diffusion-Android/releases/tag/0.5.2

The difflog is 1.1Gb (!!):
[sdai2.log.7z.001.zip](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12619131/sdai2.log.7z.001.zip)
[sdai2.log.7z.002.zip](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12619132/sdai2.log.7z.002.zip)
[sdai2.log.7z.003.zip](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12619143/sdai2.log.7z.003.zip)
(remove `.zip` from all names, then unpack `.001`)

fyi @linsui @obfusk

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/4fc53aa63a3fbf644ed1a105fa4a1cd3c9e0c8a9
/LE2: added diff log

**Comment by obfusk** [comment]
I'm guessing the problem is the dependency `onnxruntimeVersion = 'latest.release'`.

Looks like upstream's APK picked up `1.15.1` (the latest version two weeks ago when their APK was built) and our build picked up `1.16.0` (the current latest version being `1.16.0-rc1` as of September 9th it seems).

**Comment by licaon-kter** [comment]
Will try to force that version then. brb

**Comment by licaon-kter** [comment]
Great detective work! That was it :tada: 

@ShiftHackZ pls reference an exact version, for reproducible reasons too, as expected, anytime we build it it should get the right version that you upstream used 'back then' :wink:
