### ISSUE TITLE
[Feature Request] Ability to use other models (checkpoints) when running locally

### ISSUE THREAD

**Issue by Foul-Tarnished** [ShiftHackZ/Stable-Diffusion-Android#95]
**Is your feature request related to a problem? Please describe.**
Me and most people find the base SD model to be pretty bad.
For example if you want to do anime/manga artstyle, it's just awful.

**Describe the solution you'd like**
Ability to import checkpoints (based on SD 1.5 arch) in .safetensors or .pth into the app
Let us use them for inference, and switch between them easily.

**Describe alternatives you've considered**
Maybe it's possible to replace the checkpoint used by default, in Android\data or whatever, but I won't mess with that.

**Additional context**
Please support importing SD 1.5 checkpoints *and* VAE

Maybe a way to easily retrieve them from HuggingFace/CivitAI with a nice UI
but not all have VAE, so it would pretty hard to make something that works with every model there

**Comment by Foul-Tarnished** [comment]
@ShiftHackZ Will you ever implement this ?

I'm sure most people will find this app pretty useless without this feature.
The base SD checkpoint is pretty bad and too generic.

Especially when you see the numbers of downloads on CivitAI for checkpoints, in millions.

LoRa embeddings etc could be great too, but not as important

**Comment by Applewubs** [comment]
Indeed interested in this, I would love to squeeze all the performance my phone can give

**Comment by Foul-Tarnished** [comment]
> Indeed interested in this, I would love to squeeze all the performance my phone can give

This has nothing to do with performance..

**Comment by Applewubs** [comment]
> > Indeed interested in this, I would love to squeeze all the performance my phone can give
> 
> This has nothing to do with performance..

Wth?, it does, the model you can download it's 1.2GB, it doesnt even uses that much resources, outside you can download or make models of even 6GB, yes maybe the phone could crash, but I want to experiment how much can I juice it!

**Comment by Foul-Tarnished** [comment]
@ShiftHackZ Does modifying models.json to have a link to another converted model would work ?
I guess I need to do .safetensors to .onnx to .ort

Also, how does the performance of this compare to 
https://github-com.translate.goog/ZTMIDGO/Android-Stable-diffusion-ONNX/ ?
