### ISSUE TITLE
inferred on the cloud or local?

### ISSUE THREAD

**Issue by cwy0110** [ShiftHackZ/Stable-Diffusion-Android#98]
The inference is completed on the cloud server or local smart phone? It is import to me.

**Comment by ShiftHackZ** [comment]
The inference is done on server side for A1111 and Horde AI configurations. For the Local Diffusion configuration everything is done on local android device (you can even use Local Diffusion in airplane mode if you pre-downloaded local checkpoint model in configuration settings).
